# Generated by Django 6.0.2 on 2026-02-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='polyline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
