# Generated by Django 6.0.2 on 2026-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
