# Generated by Django 6.0.2 on 2026-02-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_total_distance_alter_trip_total_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cycle_used_input',
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_cycle_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_driving_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_logs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_total_work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
