# Generated by Django 6.0.2 on 2026-02-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_cycle_used_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segments', models.JSONField()),
                ('total_driving', models.FloatField(default=0)),
                ('total_on_duty', models.FloatField(default=0)),
                ('total_off_duty', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_days', to='trips.trip')),
            ],
        ),
    ]
